glossary_mapping = {
    "2006_Cornelsen_Arbeitslehre Wirtschaft_7-8_modified_kdk": "2006_Cornelsen_Arbeitslehre Wirtschaft7-8",
    "2006_Cornelsen_PolitikundWirtschaft_8_Gymnasium_Niedersachsen_modified-plain": "2006_Cornelsen_Politik und WIrtschaft 8 Gymnasium Niedersachsen",
    "2007_Cornelsen_Arbeitslehre Wirtschaft 9-10_modified": "2007_Cornelsen_Arbeitslehre Wirtschaft 9-10",
    "2007_Cornelsen_Politik und Wirtschaft 9-10_Gymnasium_Niedersachsen_edited": "2007_Cornelsen_Politik und Wirtschaft 9-10_Gymnasium_Niedersachsen",
    "2012_Cornelsen_Klick 2_Arbeitslehre-Wirtschaft_edited_lbg": "2012_Cornelsen_Klick2_Glossar",
    "2012_Cornelsen_Profilfach Wirtschaft 1_Niedersachsen_edited": "2012_Cornelsen_Profilfach Wirtschaft 1_Niedersachsen",
    "2012_Schroedel_ Stark in... Arbeit und Wirtschaft_edited": "2012_Schroedel_Stark in...Arbeit und Wirtschaft_Glossar",
    "2013_Schöningh_Politik-Wirtschaft 9-10_Schöningh_edited_lbg": "2013_Schöningh_Politik-Wirtschaft 9-10",
    "2014_Cornelsen_Wirtschaft 7-8 Differenzierende Ausgabe Niedersachsen_edited": "2014_Cornelsen_Wirtschaft 7-8 Differenzierende Ausgabe Niedersachsen",
    "2014_Cornelsen_Wirtschaft 9-10 Differenzierende Ausgabe Niedersachsen_edited": "2014_Cornelsen_Wirtschaft 9-10 Differenzierende Ausgabe Niedersachsen",
    "2015_C.C.Buchner_Politik&Co. 1_Politik-Wirtschaft f++r das Gymnasium Niedersachsen_edited": "2015_C.C.Buchner_Politik&Co. 1_Politik-Wirtschaft für das Gymnasium Niedersachsen",
    "2017_Klett_Einblicke Wirtschaft-differenzierende Ausgabe Niedersachsen_edited_lbg": "2017_Klett_Einblicke Wirtschaft-differenzierende Ausgabe Niedersachsen",
    "2010_Westermann_Praxis Wirtschaft 7-8_Sachsen-Anhalt_Ti": "2010_Westermann_Praxis Wirtschaft 7-8_Sachsen-Anhalt_Register",
    "2010_Westermann_Wirtschaft 9-10_Niedersachsen_Ti": "2010_Westermann_Wirtschaft 9-10_Niedersachsen_Register",
    "2012_Cornelsen_Profilfach Wirtschaft 1_Niedersachsen_Ti": "2012_Cornelsen_Profilfach Wirtschaft 1_Niedersachsen",
    "2013_Westermann_Praxis Arbeitslehre 1_Hessen_Ti": "2013_Westermann_Praxis Arbeitslehre 1_Hessen_Register",
    "2013_Westermann_Praxis Arbeitslehre-Wirtschaft 9-10_NRW_akd": "2013_Westermann_Praxis Arbeitslehre-Wirtschaft 9-10_NRW_Register",
    "2014_Westermann_Praxis Wirtschaft 2_Niedersachsen_akd": "2014_Westermann_Praxis WIrtschaft 2_Niedersachsen_Glossar",
    "2017_Einblicke Wirtschaft Gesamtband_ti": "2017_Klett_Einblicke Wirtschaft_Glossar",
}
